In [4]:
import numpy as np

In [6]:
import scanpy as sc

# Load the example dataset
adata = sc.datasets.pbmc3k_processed()

# Basic filtering (if further preprocessing needed, add here)
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)



In [7]:
adata.X

array([[-0.21458222, -0.37265295, -0.05480444, ..., -0.26684406,
        -0.31314576, -0.5966544 ],
       [-0.37688747, -0.2950843 , -0.0575275 , ..., -0.15865596,
        -0.17087643,  1.379     ],
       [-0.26724243,  2.4232497 , -0.05463577, ..., -0.20370372,
        -0.24683036, -0.55069876],
       ...,
       [-0.39929074, -0.34346455, -0.06179416, ..., -0.24740557,
        -0.22577284,  1.01311   ],
       [-0.290368  ,  2.6383052 , -0.0545098 , ..., -0.17459263,
        -0.21671377, -0.5298701 ],
       [-0.3863434 ,  2.6526964 , -0.05868572, ..., -0.17898981,
        -0.18173616, -0.5020216 ]], dtype=float32)

In [8]:
adata.X[0, :] = 0.

In [9]:
adata.X

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.37688747, -0.2950843 , -0.0575275 , ..., -0.15865596,
        -0.17087643,  1.379     ],
       [-0.26724243,  2.4232497 , -0.05463577, ..., -0.20370372,
        -0.24683036, -0.55069876],
       ...,
       [-0.39929074, -0.34346455, -0.06179416, ..., -0.24740557,
        -0.22577284,  1.01311   ],
       [-0.290368  ,  2.6383052 , -0.0545098 , ..., -0.17459263,
        -0.21671377, -0.5298701 ],
       [-0.3863434 ,  2.6526964 , -0.05868572, ..., -0.17898981,
        -0.18173616, -0.5020216 ]], dtype=float32)

In [10]:
sc.pp.normalize_total(adata, target_sum=1e4)

/opt/anaconda3/envs/bioma/lib/python3.11/site-packages/scanpy/preprocessing/_normalization.py:234: UserWarning: Some cells have zero counts
  warn(UserWarning("Some cells have zero counts"))


In [11]:
adata.X

array([[    0.       ,     0.       ,     0.       , ...,     0.       ,
            0.       ,     0.       ],
       [ -246.97336  ,  -193.36797  ,   -37.69762  , ...,  -103.96683  ,
         -111.97487  ,   903.655    ],
       [   53.411053 ,  -484.3105   ,    10.9195   , ...,    40.712208 ,
           49.331497 ,   110.06261  ],
       ...,
       [  -26.608313 ,   -22.888115 ,    -4.1178975, ...,   -16.486845 ,
          -15.045263 ,    67.51258  ],
       [  -31.869257 ,   289.56644  ,    -5.9827075, ...,   -19.162365 ,
          -23.785358 ,   -58.155743 ],
       [  345.9963   , -2375.6667   ,    52.556984 , ...,   160.29733  ,
          162.75687  ,   449.59387  ]], dtype=float32)

In [12]:
adata.X[0, :] = -1.

In [13]:
sc.pp.normalize_total(adata, target_sum=1e4)

In [15]:
adata.X

array([[    5.473454 ,     5.473454 ,     5.473454 , ...,     5.473454 ,
            5.473454 ,     5.473454 ],
       [ -246.97324  ,  -193.36787  ,   -37.6976   , ...,  -103.96678  ,
         -111.974815 ,   903.6546   ],
       [   53.411053 ,  -484.3105   ,    10.9195   , ...,    40.712208 ,
           49.331497 ,   110.06261  ],
       ...,
       [  -26.608313 ,   -22.888115 ,    -4.1178975, ...,   -16.486845 ,
          -15.045263 ,    67.51258  ],
       [  -31.869257 ,   289.56644  ,    -5.9827075, ...,   -19.162365 ,
          -23.785358 ,   -58.155743 ],
       [  345.9961   , -2375.6653   ,    52.556953 , ...,   160.29724  ,
          162.75677  ,   449.5936   ]], dtype=float32)

In [16]:
adata.X.sum(1)

array([10000.002,  9999.994, 10000.   , 10000.   , 10000.   , 10000.   ,
       10000.   , 10000.003, 10000.023, 10000.   , 10000.   , 10000.   ,
       10000.   ,  9999.998, 10000.   , 10000.   , 10000.001, 10000.007,
       10000.001, 10000.   , 10000.   , 10000.   , 10000.   , 10000.   ,
        9999.98 , 10000.   ,  9999.992, 10000.   , 10000.001, 10000.   ,
       10000.   ,  9999.998, 10000.016, 10000.   ,  9999.999, 10000.002,
        9999.998,  9999.999, 10000.001, 10000.004,  9999.999, 10000.   ,
       10000.002, 10000.   , 10000.   , 10000.   , 10000.   ,  9999.998,
       10000.001, 10000.008, 10000.   ,  9999.996, 10000.   , 10000.001,
        9999.999, 10000.   , 10000.   , 10000.   , 10000.   , 10000.006,
       10000.   , 10000.   , 10000.   , 10000.   , 10000.   , 10000.   ,
        9999.999, 10000.   , 10000.016, 10000.001, 10000.   , 10000.001,
       10000.   , 10000.   , 10000.   , 10000.   ,  9999.998, 10000.   ,
       10000.   , 10000.   ,  9999.998, 10000.   , 

In [18]:
adata.X[0,:] = 0
adata.X[0,-2] = 1
adata.X[0,-1] = -1

In [19]:
adata.X

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  1.00000000e+00, -1.00000000e+00],
       [-2.46973236e+02, -1.93367874e+02, -3.76976013e+01, ...,
        -1.03966782e+02, -1.11974815e+02,  9.03654602e+02],
       [ 5.34110527e+01, -4.84310486e+02,  1.09195004e+01, ...,
         4.07122078e+01,  4.93314972e+01,  1.10062607e+02],
       ...,
       [-2.66083126e+01, -2.28881149e+01, -4.11789751e+00, ...,
        -1.64868450e+01, -1.50452633e+01,  6.75125809e+01],
       [-3.18692570e+01,  2.89566437e+02, -5.98270750e+00, ...,
        -1.91623650e+01, -2.37853584e+01, -5.81557426e+01],
       [ 3.45996094e+02, -2.37566528e+03,  5.25569534e+01, ...,
         1.60297241e+02,  1.62756775e+02,  4.49593597e+02]], dtype=float32)

In [20]:
sc.pp.normalize_total(adata, target_sum=1e4)

In [21]:
adata.X

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  1.00000000e+00, -1.00000000e+00],
       [-2.46973389e+02, -1.93367996e+02, -3.76976242e+01, ...,
        -1.03966843e+02, -1.11974884e+02,  9.03655151e+02],
       [ 5.34110527e+01, -4.84310486e+02,  1.09195004e+01, ...,
         4.07122078e+01,  4.93314972e+01,  1.10062607e+02],
       ...,
       [-2.66083126e+01, -2.28881149e+01, -4.11789751e+00, ...,
        -1.64868450e+01, -1.50452633e+01,  6.75125809e+01],
       [-3.18692570e+01,  2.89566437e+02, -5.98270750e+00, ...,
        -1.91623650e+01, -2.37853584e+01, -5.81557426e+01],
       [ 3.45996155e+02, -2.37566577e+03,  5.25569611e+01, ...,
         1.60297272e+02,  1.62756805e+02,  4.49593689e+02]], dtype=float32)

In [22]:
adata.X.sum(1)

array([    0.   , 10000.007, 10000.   , 10000.   , 10000.   , 10000.   ,
       10000.   ,  9999.998, 10000.023, 10000.   , 10000.   , 10000.   ,
       10000.   , 10000.002, 10000.   , 10000.   ,  9999.998,  9999.992,
        9999.999, 10000.   , 10000.   , 10000.   , 10000.   , 10000.   ,
       10000.004, 10000.   , 10000.004, 10000.   ,  9999.998, 10000.   ,
       10000.   , 10000.001,  9999.984, 10000.   , 10000.   ,  9999.999,
       10000.008, 10000.   ,  9999.999,  9999.996,  9999.999, 10000.   ,
       10000.001, 10000.   , 10000.   , 10000.   , 10000.   , 10000.001,
        9999.999,  9999.992, 10000.   , 10000.003, 10000.   , 10000.   ,
       10000.002, 10000.   , 10000.   , 10000.   , 10000.   ,  9999.994,
       10000.   , 10000.   , 10000.   , 10000.   , 10000.   , 10000.   ,
       10000.001, 10000.   ,  9999.984,  9999.998, 10000.   ,  9999.999,
       10000.   , 10000.   , 10000.   , 10000.   , 10000.001, 10000.   ,
       10000.   , 10000.   , 10000.002, 10000.   , 